baseURL = 'https://nicolau.github.io/'
locale = 'en-us'
title = 'PhD Andre NA Goncalves'
theme='PaperMod'

enableRobotsTXT= true

[params]
  env = "production"
  author = "Andre Goncalves"
  description = "Andre's personal website"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "Hi, I'm Andre Goncalves"
    subtitle = "Senior postdoc and computational biologist. Developer, maker, and curious human."
    imageUrl = "/images/general/profile.png"
    imageWidth = 160
    imageHeight = 160
    imageTitle = "PhD Andre Goncalves"

    [[params.profileMode.buttons]]
      name = "Blog"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "About"
      url = "about"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/nicolau"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:andre.goncalves@paediatrics.ox.ac.uk"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/andre-nicolau-aquime-goncalves/"

[menu]
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
  
  [[menu.main]]
    identifier = "career"
    name = "Career"
    url = "/career/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40